In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../01 Prueba quitando eventos/03desastreslimpio 4eventos.csv')
df.head()

,Dis No,Year,Seq,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,ISO,Region,Continent,...,Longitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,Total Affected,Total Damages Adj
0,1900-9002-CPV,1900,9002,Climatological,Drought,Drought,Cabo Verde,CPV,Western Africa,Africa,...,NaN,1900,0,0,1900,0,0,11000,0,0
1,1900-9001-IND,1900,9001,Climatological,Drought,Drought,India,IND,Southern Asia,Asia,...,NaN,1900,0,0,1900,0,0,1250000,0,0
2,1902-0012-GTM,1902,12,Geophysical,Earthquake,Ground movement,Guatemala,GTM,Central America,Americas,...,-91,1902,4,18,1902,4,18,2000,0,843726
3,1902-0003-GTM,1902,3,Geophysical,Volcanic activity,Ash fall,Guatemala,GTM,Central America,Americas,...,NaN,1902,4,8,1902,4,8,1000,0,0
4,1902-0010-GTM,1902,10,Geophysical,Volcanic activity,Ash fall,Guatemala,GTM,Central America,Americas,...,NaN,1902,10,24,1902,10,24,6000,0,0

In [4]:
df.shape

(16636, 26)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16636 entries, 0 to 16635
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Dis No             16636 non-null  object
 1   Year               16636 non-null  int64
 2   Seq                16636 non-null  int64
 3   Disaster Subgroup  16636 non-null  object
 4   Disaster Type      16636 non-null  object
 5   Disaster Subtype   13313 non-null  object
 6   Country            16636 non-null  object
 7   ISO                16636 non-null  object
 8   Region             16636 non-null  object
 9   Continent          16636 non-null  object
 10  Location           14825 non-null  object
 11  Origin             4085 non-null   object
 12  Associated Dis     3593 non-null   object
 13  Dis Mag Value      16636 non-null  int64
 14  Dis Mag Scale      15416 non-null  object
 15  Latitude           2775 non-null   object
 16  Longitude          2775 non-null   object
 17  Start Year         16636 non-null  int64
 18  Start Month        16636 non-null  int64
 19  Start Day          16636 non-null  int64
 20  End Year           16636 non-null  int64
 21  End Month          16636 non-null  int64
 22  End Day            16636 non-null  int64
 23  Total Deaths       16636 non-null  int64
 24  Total Affected     16636 non-null  int64
 25  Total Damages Adj  16636 non-null  int64
dtypes: int64(12), object(14)
memory usage: 3.3+ MB

In [6]:
# Columnas nÃºmericas
df.select_dtypes(include=np.number).columns.to_list()

['Year',
 'Seq',
 'Dis Mag Value',
 'Start Year',
 'Start Month',
 'Start Day',
 'End Year',
 'End Month',
 'End Day',
 'Total Deaths',
 'Total Affected',
 'Total Damages Adj']

In [8]:
df.isnull().sum()

Dis No                   0
Year                     0
Seq                      0
Disaster Subgroup        0
Disaster Type            0
Disaster Subtype      3323
Country                  0
ISO                      0
Region                   0
Continent                0
Location              1811
Origin               12551
Associated Dis       13043
Dis Mag Value            0
Dis Mag Scale         1220
Latitude             13861
Longitude            13861
Start Year               0
Start Month              0
Start Day                0
End Year                 0
End Month                0
End Day                  0
Total Deaths             0
Total Affected           0
Total Damages Adj        0
dtype: int64

In [9]:
# Filtrar y mantener las filas que contienen los 4 eventos con mÃ¡s impacto bien sea humano o econÃ³mico
eventos_con_mas_impacto = ["Flood", "Storm", "Earthquake", "Drought"]

df = df[df['Disaster Type'].isin(eventos_con_mas_impacto)]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12826 entries, 0 to 16634
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Dis No             12826 non-null  object
 1   Year               12826 non-null  int64
 2   Seq                12826 non-null  int64
 3   Disaster Subgroup  12826 non-null  object
 4   Disaster Type      12826 non-null  object
 5   Disaster Subtype   9766 non-null   object
 6   Country            12826 non-null  object
 7   ISO                12826 non-null  object
 8   Region             12826 non-null  object
 9   Continent          12826 non-null  object
 10  Location           11583 non-null  object
 11  Origin             3680 non-null   object
 12  Associated Dis     3360 non-null   object
 13  Dis Mag Value      12826 non-null  int64
 14  Dis Mag Scale      12826 non-null  object
 15  Latitude           2659 non-null   object
 16  Longitude          2659 non-null   object
 17  Start Year         12826 non-null  int64
 18  Start Month        12826 non-null  int64
 19  Start Day          12826 non-null  int64
 20  End Year           12826 non-null  int64
 21  End Month          12826 non-null  int64
 22  End Day            12826 non-null  int64
 23  Total Deaths       12826 non-null  int64
 24  Total Affected     12826 non-null  int64
 25  Total Damages Adj  12826 non-null  int64
dtypes: int64(12), object(14)
memory usage: 2.6+ MB

In [12]:
df.shape

(12826, 26)

In [13]:
df.head(20)

,Dis No,Year,Seq,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,ISO,Region,Continent,...,Longitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,Total Affected,Total Damages Adj
0,1900-9002-CPV,1900,9002,Climatological,Drought,Drought,Cabo Verde,CPV,Western Africa,Africa,...,NaN,1900,0,0,1900,0,0,11000,0,0
1,1900-9001-IND,1900,9001,Climatological,Drought,Drought,India,IND,Southern Asia,Asia,...,NaN,1900,0,0,1900,0,0,1250000,0,0
2,1902-0012-GTM,1902,12,Geophysical,Earthquake,Ground movement,Guatemala,GTM,Central America,Americas,...,-91,1902,4,18,1902,4,18,2000,0,843726
7,1904-0003-BGD,1904,3,Meteorological,Storm,Tropical cyclone,Bangladesh,BGD,Southern Asia,Asia,...,NaN,1904,11,0,1904,11,0,0,0,0
9,1905-0003-IND,1905,3,Geophysical,Earthquake,Ground movement,India,IND,Southern Asia,Asia,...,76.16,1905,4,4,1905,4,4,20000,0,812477
10,1906-0014-CHL,1906,14,Geophysical,Earthquake,Ground movement,Chile,CHL,South America,Americas,...,71.4,1906,8,16,1906,8,16,20000,0,3249907
11,1906-0002-COL,1906,2,Geophysical,Earthquake,Ground movement,Colombia,COL,South America,Americas,...,-78.46,1906,1,31,1906,1,31,400,0,0
12,1906-0023-BEL,1906,23,Hydrological,Flood,NaN,Belgium,BEL,Western Europe,Europe,...,NaN,1906,5,14,1906,5,14,6,0,0
13,1906-0024-BEL,1906,24,Hydrological,Flood,NaN,Belgium,BEL,Western Europe,Europe,...,NaN,1906,4,0,1906,4,0,0,0,0
14,1906-0015-HKG,1906,15,Meteorological,Storm,Tropical cyclone,Hong Kong,HKG,Eastern Asia,Asia,...,NaN,1906,9,8,1906,9,8,10000,0,649981
15,1907-0006-CHN,1907,6,Geophysical,Earthquake,Ground movement,China,CHN,Eastern Asia,Asia,...,69.9,1907,10,21,1907,10,21,12000,0,0
18,1909-0010-BGD,1909,10,Meteorological,Storm,Tropical cyclone,Bangladesh,BGD,Southern Asia,Asia,...,NaN,1909,10,15,1909,10,15,172,0,0
19,1909-0013-BGD,1909,13,Meteorological,Storm,Tropical cyclone,Bangladesh,BGD,Southern Asia,Asia,...,NaN,1909,12,0,1909,12,0,0,0,0
21,1909-0009-FRA,1909,9,Geophysical,Earthquake,Ground movement,France,FRA,Western Europe,Europe,...,6.14,1909,6,11,1909,6,11,46,0,0
22,1909-0012-HTI,1909,12,Meteorological,Storm,Tropical cyclone,Haiti,HTI,Caribbean,Americas,...,NaN,1909,11,12,1909,11,12,150,0,0
24,1910-9006-BFA,1910,9006,Climatological,Drought,Drought,Burkina Faso,BFA,Western Africa,Africa,...,NaN,1910,0,0,1914,0,0,0,0,0
27,1910-9006-CPV,1910,9006,Climatological,Drought,Drought,Cabo Verde,CPV,Western Africa,Africa,...,NaN,1910,0,0,1914,0,0,0,0,0
28,1910-0004-CRI,1910,4,Geophysical,Earthquake,Ground movement,Costa Rica,CRI,Central America,Americas,...,-84,1910,4,13,1910,4,13,1750,0,0
29,1910-0005-DZA,1910,5,Geophysical,Earthquake,Ground movement,Algeria,DZA,Northern Africa,Africa,...,4,1910,6,24,1910,6,24,12,0,0
30,1910-9006-GMB,1910,9006,Climatological,Drought,Drought,Gambia (the),GMB,Western Africa,Africa,...,NaN,1910,0,0,1914,0,0,0,0,0

In [14]:
df2 = df.copy()

In [15]:
df2.to_csv('../01 Prueba quitando eventos/04DesNat_DEFS_limpio_fc.csv', index=False)